unitDef = {
  unitname            = [[armarad]],
  name                = [[Advanced Radar Tower]],
  description         = [[Long-Range Radar, decreases radar wobble]],
  acceleration        = 0,
  activateWhenBuilt   = true,
  bmcode              = [[0]],
  brakeRate           = 0,
  buildAngle          = 8192,
  buildCostEnergy     = 500,
  buildCostMetal      = 500,
  builder             = false,
  buildPic            = [[ARMARAD.png]],
  buildTime           = 500,
  canAttack           = false,
  category            = [[UNARMED FLOAT]],
  collisionVolumeTest = 1,
  corpse              = [[DEAD]],
  energyUse           = 3,
  explodeAs           = [[SMALL_BUILDINGEX]],
  floater             = true,
  footprintX          = 2,
  footprintZ          = 2,
  iconType            = [[radar]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  isTargetingUpgrade  = true,
  levelGround         = false,
  mass                = 250,
  maxangledif1        = [[1]],
  maxDamage           = 320,
  maxSlope            = 36,
  maxVelocity         = 0,
  minCloakDistance    = 150,
  noAutoFire          = false,
  objectName          = [[ARMARAD]],
  onoffable           = true,
  radarDistance       = 4000,
  seismicSignature    = 4,
  selfDestructAs      = [[SMALL_BUILDINGEX]],
  side                = [[ARM]],
  sightDistance       = 800,
  smoothAnim          = true,
  TEDClass            = [[SPECIAL]],
  turnRate            = 0,
  workerTime          = 0,
  yardMap             = [[oooo]],

  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - Advanced Radar Tower]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 640,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[40]],
      hitdensity       = [[100]],
      metal            = 250,
      object           = [[ARMARAD_DEAD]],
      reclaimable      = true,
      reclaimTime      = 250,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Advanced Radar Tower]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 640,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 250,
      object           = [[debris2x2b.s3o]],
      reclaimable      = true,
      reclaimTime      = 250,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Advanced Radar Tower]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 640,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 125,
      object           = [[debris2x2b.s3o]],
      reclaimable      = true,
      reclaimTime      = 125,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ armarad = unitDef })
