unitDef = {
  unitname            = [[armasp]],
  name                = [[Air Repair Pad]],
  description         = [[Automatically Repairs Aircraft]],
  acceleration        = 0,
  activateWhenBuilt   = true,
  bmcode              = [[0]],
  brakeRate           = 0,
  buildAngle          = 0,
  buildCostEnergy     = 350,
  buildCostMetal      = 350,
  buildDistance       = 6,
  builder             = true,

  buildoptions        = {
  },

  buildPic            = [[ARMASP.png]],
  buildTime           = 350,
  category            = [[UNARMED FLOAT]],
  collisionVolumeTest = 1,
  corpse              = [[DEAD]],

  customParams        = {
    helptext = [[The Air Repair Pad repairs up to four aircraft at a time. It also refuels/rearms bombers.]],
  },

  explodeAs           = [[LARGE_BUILDINGEX]],
  footprintX          = 9,
  footprintZ          = 9,
  iconType            = [[building]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  isAirBase           = true,
  mass                = 100000,
  maxDamage           = 1860,
  maxSlope            = 18,
  maxVelocity         = 0,
  minCloakDistance    = 150,
  noAutoFire          = false,
  objectName          = [[airpad.s3o]],
  onoffable           = true,
  seismicSignature    = 4,
  selfDestructAs      = [[LARGE_BUILDINGEX]],
  side                = [[ARM]],
  sightDistance       = 273,
  smoothAnim          = true,
  sortbias            = [[0]],
  turnRate            = 0,
  waterline           = 1,
  workerTime          = 12,
  yardMap             = [[ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo]],

  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - Air Repair Pad]],
      blocking         = false,
      category         = [[corpses]],
      damage           = 3720,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      height           = [[40]],
      hitdensity       = [[100]],
      metal            = 175,
      object           = [[ARMASP_DEAD]],
      reclaimable      = true,
      reclaimTime      = 175,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Air Repair Pad]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 3720,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 1,
      footprintZ       = 1,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 175,
      object           = [[debris4x4a.s3o]],
      reclaimable      = true,
      reclaimTime      = 175,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Air Repair Pad]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 3720,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 1,
      footprintZ       = 1,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 87.5,
      object           = [[debris4x4a.s3o]],
      reclaimable      = true,
      reclaimTime      = 87.5,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ armasp = unitDef })
