unitDef = {
  unitname          = [[armmstor]],
  name              = [[Metal Storage]],
  description       = [[Stores Metal (500)]],
  acceleration      = 0,
  activateWhenBuilt = true,
  bmcode            = [[0]],
  brakeRate         = 0,
  buildAngle        = 4096,
  buildCostEnergy   = 80,
  buildCostMetal    = 80,
  builder           = false,
  buildPic          = [[ARMMSTOR.png]],
  buildTime         = 80,
  category          = [[SINK UNARMED]],
  corpse            = [[DEAD]],
  explodeAs         = [[SMALL_BUILDINGEX]],
  footprintX        = 4,
  footprintZ        = 4,
  iconType          = [[mex]],
  idleAutoHeal      = 5,
  idleTime          = 1800,
  mass              = 40,
  maxDamage         = 700,
  maxSlope          = 18,
  maxVelocity       = 0,
  metalStorage      = 500,
  minCloakDistance  = 150,
  noAutoFire        = false,
  objectName        = [[ARMUWADVMS]],
  seismicSignature  = 4,
  selfDestructAs    = [[SMALL_BUILDINGEX]],
  side              = [[ARM]],
  sightDistance     = 273,
  smoothAnim        = true,
  TEDClass          = [[METAL]],
  turnRate          = 0,
  workerTime        = 0,
  yardMap           = [[oooooooooooooooo]],

  featureDefs       = {

    DEAD  = {
      description      = [[Wreckage - Metal Storage]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 1400,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      height           = [[40]],
      hitdensity       = [[100]],
      metal            = 40,
      object           = [[ARMUWADVMS_DEAD]],
      reclaimable      = true,
      reclaimTime      = 40,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Metal Storage]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 1400,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 40,
      object           = [[debris4x4c.s3o]],
      reclaimable      = true,
      reclaimTime      = 40,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Metal Storage]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 1400,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 20,
      object           = [[debris4x4c.s3o]],
      reclaimable      = true,
      reclaimTime      = 20,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ armmstor = unitDef })
