unitDef = {
  unitname          = [[corfus]],
  name              = [[Graviton Power Generator]],
  description       = [[Produces Energy (35)]],
  acceleration      = 0,
  activateWhenBuilt = true,
  bmcode            = [[0]],
  brakeRate         = 0,
  buildAngle        = 16384,
  buildCostEnergy   = 1000,
  buildCostMetal    = 1000,
  builder           = false,
  buildPic          = [[CORFUS.png]],
  buildTime         = 1000,
  category          = [[SINK UNARMED]],
  corpse            = [[DEAD]],

  customParams      = {
    helptext = [[Graviton generators provide a good amount of steady energy output at a fair price. They are attractive targets and not very well-armored, so keep them well-protected. When killed, graviton generators will cause heavy damage to nearby units.]],
	pylonrange = 450,
  },

  energyMake        = 35,
  energyUse         = 0,
  explodeAs         = [[ATOMIC_BLAST]],
  footprintX        = 5,
  footprintZ        = 5,
  iconType          = [[energy2]],
  idleAutoHeal      = 5,
  idleTime          = 1800,
  mass              = 500,
  maxDamage         = 2200,
  maxSlope          = 18,
  maxVelocity       = 0,
  minCloakDistance  = 150,
  noAutoFire        = false,
  objectName        = [[corfus.s3o]],
  seismicSignature  = 4,
  selfDestructAs    = [[ATOMIC_BLAST]],
  side              = [[CORE]],
  sightDistance     = 273,
  smoothAnim        = true,
  TEDClass          = [[ENERGY]],
  turnRate          = 0,
  workerTime        = 0,
  yardMap           = [[ooooooooooooooooooooooooo]],

  featureDefs       = {

    DEAD  = {
      description      = [[Wreckage - Graviton Power Generator]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 4400,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 5,
      footprintZ       = 5,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 500,
      object           = [[CORFUS_DEAD]],
      reclaimable      = true,
      reclaimTime      = 500,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Graviton Power Generator]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 4400,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 5,
      footprintZ       = 5,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 500,
      object           = [[debris4x4b.s3o]],
      reclaimable      = true,
      reclaimTime      = 500,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Graviton Power Generator]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 4400,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 5,
      footprintZ       = 5,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 250,
      object           = [[debris4x4b.s3o]],
      reclaimable      = true,
      reclaimTime      = 250,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ corfus = unitDef })
