unitDef = {
  unitname              = [[logareamine]],
  name                  = [[Demo]],
  description           = [[Napalm Cluster Trap Mine]],
  acceleration          = 0,
  activateWhenBuilt     = true,
  bmcode                = [[0]],
  brakeRate             = 0,
  buildCostEnergy       = 80,
  buildCostMetal        = 80,
  builder               = false,
  buildPic              = [[CORMINE1.png]],
  buildTime             = 80,
  canAttack             = false,
  canGuard              = false,
  canMove               = false,
  canPatrol             = false,
  canstop               = [[0]],
  category              = [[FLOAT FIREPROOF]],
  cloakCost             = 0,

  customParams          = {
    dontCount = [[1]],
    fireproof      = [[1]],
  },

  defaultmissiontype    = [[Standby_Mine]],
  explodeAs             = [[MINE_LOGOS_AREA]],
  footprintX            = 1,
  footprintZ            = 1,
  iconType              = [[mine]],
  idleAutoHeal          = 25,
  idleTime              = 100,
  initCloaked           = true,
  kamikaze              = true,
  kamikazeDistance      = 160,
  mass                  = 2.5,
  maxDamage             = 300,
  maxSlope              = 255,
  maxVelocity           = 0,
  minCloakDistance      = 50,
  noAutoFire            = true,
  noChaseCategory       = [[FIXEDWING LAND SINK SHIP SATELLITE SWIM GUNSHIP FLOAT SUB HOVER]],
  objectName            = [[logmine.s3o]],
  onoffable             = false,
  seismicDistance       = 80,
  seismicSignature      = 16,
  selfDestructAs        = [[MINE_LOGOS_AREA]],
  selfDestructCountdown = 0,
  side                  = [[CORE]],
  sightDistance         = -1,
  smoothAnim            = true,
  stealth               = true,
  TEDClass              = [[SPECIAL]],
  turnRate              = 0,
  waterline             = 1,
  workerTime            = 0,
  yardMap               = [[o]],

  weapons               = {

    {
      def                = [[NAPALM_CLUSTERS]],
      onlyTargetCategory = [[NONE]],
	  mainDir            = [[0 1 0]],
      maxAngleDif        = 200,
    },

  },

  weaponDefs            = {
	
    NAPALM_CLUSTERS = {
      name                    = [[Flame Cluster Detonation]],
      areaOfEffect            = 155,
	  edgeEffectiveness		= 0.8,
      craterBoost             = 0.7,
      craterMult              = 0.4,
      damage                  = {
        default = 30,
        subs    = 5,
      },

      explosionGenerator      = [[custom:NAPALM_Expl]],
	  FixedLauncher 		= true,
	  --BurnBlow					= true,
	  tolerance 			= 9999,
      fireStarter             = 260,
      flameGfxTime            = 0.3,
      impulseBoost            = 0.7,
      impulseFactor           = 1.2,
      interceptedByShieldType = 2,
      lineOfSight             = true,
      model                   = [[bomb]],
      noSelfDamage            = true,
      range                   = 180,
	  flightTime			= 0.5,
      myGravity               = 0.5,
      reloadtime              = 1,
      renderType              = 4,
      smokeTrail              = true,
      soundHit                = [[OTAunit/XPLOSML2]],
      soundHitVolume          = 8,
      soundStart              = [[openQuarz/sattck1]],
      soundStartVolume        = 2,
      sprayangle              = 850,
      startsmoke              = [[1]],
      startVelocity           = 95,
      turret                  = true,
      weaponAcceleration      = 75,
      weaponTimer             = 3,
      weaponType              = [[MissileLauncher]],
      weaponVelocity          = 160,
    },
	
  },

}

return lowerkeys({ logareamine = unitDef })
