unitDef = {
  unitname              = [[logheavymine]],
  name                  = [[Gali]],
  description           = [[High Intensity Impulse Trap Mine]],
  acceleration          = 0,
  activateWhenBuilt     = true,
  bmcode                = [[0]],
  brakeRate             = 0,
  buildCostEnergy       = 180,
  buildCostMetal        = 180,
  builder               = false,
  buildPic              = [[CORMINE1.png]],
  buildTime             = 180,
  canAttack             = false,
  canGuard              = false,
  canMove               = false,
  canPatrol             = false,
  canstop               = [[0]],
  category              = [[FLOAT]],
  cloakCost             = 0,
  script				= [[logheavymine.lua]],

  customParams          = {
    dontCount = [[1]],
  },

  defaultmissiontype    = [[Standby_Mine]],
  explodeAs             = [[MINE_LOGOS_HEAVY]],
  footprintX            = 1,
  footprintZ            = 1,
  iconType              = [[mine]],
  idleAutoHeal          = 15,
  idleTime              = 150,
  initCloaked           = true,
  kamikaze              = true,
  kamikazeDistance      = 80,
  mass                  = 2.5,
  maxDamage             = 400,
  maxSlope              = 255,
  maxVelocity           = 0,
  minCloakDistance      = 50,
  noAutoFire            = true,
  noChaseCategory       = [[FIXEDWING LAND SINK SHIP SATELLITE SWIM GUNSHIP FLOAT SUB HOVER]],
  objectName            = [[galimine.s3o]],
  onoffable             = false,
  seismicDistance       = 80,
  seismicSignature      = 16,
  selfDestructAs        = [[MINE_LOGOS_HEAVY]],
  selfDestructCountdown = 0,
  side                  = [[CORE]],
  sightDistance         = -1,
  smoothAnim            = true,
  stealth               = true,
  TEDClass              = [[SPECIAL]],
  turnRate              = 0,
  waterline             = 1,
  workerTime            = 0,
  yardMap               = [[o]],

  }

return lowerkeys({ logheavymine = unitDef })