unitDef = {
  unitname            = [[logkoda]],
  name                = [[Kodachi]],
  description         = [[Raider Tank]],
  acceleration        = 0.125,
  bmcode              = [[1]],
  brakeRate           = 0.125,
  buildCostEnergy     = 260,
  buildCostMetal      = 260,
  builder             = false,
  buildPic            = [[logkoda.png]],
  buildTime           = 260,
  canAttack           = true,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canstop             = [[1]],
  category            = [[LAND]],
  corpse              = [[DEAD]],

  customParams        = {
    fireproof = [[1]],
    helptext  = [[The diminutive Kodachi is a unique raider. Its small yet agile chassis has enough armor and speed to get it close enough to fire its weapon, a napalm cluster bomb. The Kodachi should run in, get a shot off, and withdraw before it takes significant damage.]],
  },

  defaultmissiontype  = [[Standby]],
  explodeAs           = [[BIG_UNITEX]],
  footprintX          = 3,
  footprintZ          = 3,
  iconType            = [[tankraider]],
  idleAutoHeal        = 10,
  idleTime            = 50,
  leaveTracks         = true,
  maneuverleashlength = [[640]],
  mass                = 130,
  maxDamage           = 895,
  maxSlope            = 18,
  maxVelocity         = 3.65,
  maxWaterDepth       = 22,
  minCloakDistance    = 75,
  movementClass       = [[TANK3]],
  noAutoFire          = false,
  noChaseCategory     = [[TERRAFORM FIXEDWING SATELLITE SUB]],
  objectName          = [[logkoda.s3o]],
  seismicSignature    = 4,
  selfDestructAs      = [[BIG_UNITEX]],
  side                = [[CORE]],
  sightDistance       = 660,
  smoothAnim          = true,
  steeringmode        = [[1]],
  TEDClass            = [[TANK]],
  trackOffset         = 6,
  trackStrength       = 5,
  trackStretch        = 1,
  trackType           = [[StdTank]],
  trackWidth          = 30,
  turninplace         = 0,
  turnRate            = 550,
  workerTime          = 0,

  weapons             = {

    {
      def                = [[NAPALM_BOMBLET]],
      badTargetCategory  = [[GUNSHIP]],
      onlyTargetCategory = [[LAND SINK SHIP SWIM FLOAT HOVER GUNSHIP]],
    },

  },


  weaponDefs          = {

    KODACHI_LASER  = {
      name                    = [[High-Energy Laser]],
      areaOfEffect            = 14,
      beamWeapon              = true,
      canattackground         = true,
      cegTag                  = [[yellowlaser_hlt]],
      coreThickness           = 0.5,
      craterBoost             = 1,
      craterMult              = 1,

      damage                  = {
        default = 500,
        planes  = 500,
        subs    = 25,
      },

      duration                = 0.05,
      energypershot           = 25,
      explosionGenerator      = [[custom:BEAMWEAPON_HIT_YELLOW]],
      fireStarter             = 90,
      heightMod               = 1,
      impactOnly              = true,
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 1,
      lineOfSight             = true,
      lodDistance             = 10000,
      noSelfDamage            = true,
      range                   = 260,
      reloadtime              = 5,
      renderType              = 0,
      rgbColor                = [[1 1 0]],
      soundHit                = [[psionic/laserhit]],
      soundStart              = [[psionic/laser]],
      sweepfire               = false,
      targetMoveError         = 0.2,
      thickness               = 8.81050509335305,
      tolerance               = 500,
      turret                  = true,
      weaponType              = [[LaserCannon]],
      weaponVelocity          = 2480,
    },


    NAPALM_BOMBLET = {
      name                    = [[Flame Bomblets]],
      areaOfEffect            = 72,
      craterBoost             = 0,
      craterMult              = 0,

      damage                  = {
        default = 100,
        planes  = 100,
        subs    = 5,
      },

      explosionGenerator      = [[custom:NAPALM_Expl]],
      fireStarter             = 200,
      flameGfxTime            = 0.1,
      impulseBoost            = 0,
      impulseFactor           = 0.2,
      interceptedByShieldType = 2,
      lineOfSight             = true,
      model                   = [[bomb]],
      noSelfDamage            = true,
      projectiles             = 5,
      range                   = 270,
      reloadtime              = 6,
      renderType              = 4,
      smokeTrail              = true,
      soundHit                = [[OTAunit/XPLOSML2]],
      soundHitVolume          = 8,
      soundStart              = [[openQuarz/sattck1]],
      soundStartVolume        = 2,
      sprayangle              = 650,
      startsmoke              = [[1]],
      startVelocity           = 350,
      turret                  = true,
      weaponAcceleration      = 190,
      weaponTimer             = 3,
      weaponType              = [[MissileLauncher]],
      weaponVelocity          = 350,
    },

  },


  featureDefs         = {

    DEAD  = {
      description      = [[Wreckage - Kodachi]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 1790,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 130,
      object           = [[CORGARP_DEAD]],
      reclaimable      = true,
      reclaimTime      = 130,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Kodachi]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 1790,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 130,
      object           = [[debris2x2c.s3o]],
      reclaimable      = true,
      reclaimTime      = 130,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Kodachi]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 1790,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 2,
      footprintZ       = 2,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 65,
      object           = [[debris2x2c.s3o]],
      reclaimable      = true,
      reclaimTime      = 65,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ logkoda = unitDef })
