unitDef = {
  unitname          = [[mexpylon]],
  name              = [[Overdrive Pylon]],
  description       = [[Overdrives nearby Metal Extractors (Maximum 3) with extra energy]],
  acceleration      = 0,
  activateWhenBuilt = true,
  bmcode            = [[0]],
  brakeRate         = 0,
  buildAngle        = 8196,
  buildCostEnergy   = 500,
  buildCostMetal    = 500,
  builder           = false,
  buildPic          = [[mexpylon.png]],
  buildTime         = 500,
  category          = [[SINK UNARMED]],
  corpse            = [[DEAD]],

  customParams      = {
    ispylon = true,
    isoverdrivepylon = true,
  },

  explodeAs         = [[ESTOR_BUILDINGEX]],
  floater           = true,
  footprintX        = 4,
  footprintZ        = 4,
  iconType          = [[energy1]],
  idleAutoHeal      = 5,
  idleTime          = 1800,
  levelGround       = false,
  mass              = 75,
  maxDamage         = 1000,
  maxSlope          = 18,
  maxVelocity       = 0,
  minCloakDistance  = 150,
  noAutoFire        = false,
  objectName        = [[AENERGYSTORAGE.s3o]],
  seismicSignature  = 4,
  selfDestructAs    = [[ESTOR_BUILDINGEX]],
  side              = [[CORE]],
  sightDistance     = 273,
  smoothAnim        = true,
  TEDClass          = [[ENERGY]],
  turnRate          = 0,
  workerTime        = 0,
  yardMap           = [[oooooooooooooooo]],

  featureDefs       = {

    DEAD  = {
      description      = [[Wreckage - Node]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 2000,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      height           = [[20]],
      hitdensity       = [[100]],
      metal            = 300,
      object           = [[AENERGYSTORAGE_DEAD.s3o]],
      reclaimable      = true,
      reclaimTime      = 300,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Node]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 2000,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 300,
      object           = [[debris4x4a.s3o]],
      reclaimable      = true,
      reclaimTime      = 300,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Node]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 2000,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 150,
      object           = [[debris4x4a.s3o]],
      reclaimable      = true,
      reclaimTime      = 150,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ mexpylon = unitDef })
