unitDef = {
  unitname          = [[pylon]],
  name              = [[Transfer Pylon]],
  description       = [[Creates connections between energy and other Pylons]],
  acceleration      = 0,
  activateWhenBuilt = true,
  brakeRate         = 0,
  buildAngle        = 4096,
  buildCostEnergy   = 100,
  buildCostMetal    = 100,
  builder           = false,
  buildPic          = [[pylon.png]],
  buildTime         = 100,
  category          = [[SINK UNARMED]],
  corpse            = [[DEAD]],

  customParams      = {
    ispylon = true,
  },

  explodeAs         = [[ESTOR_BUILDINGEX]],
  floater           = true,
  footprintX        = 3,
  footprintZ        = 3,
  iconType          = [[energy1]],
  idleAutoHeal      = 5,
  idleTime          = 1800,
  levelGround       = false,
  mass              = 75,
  maxDamage         = 1000,
  maxSlope          = 18,
  maxVelocity       = 0,
  minCloakDistance  = 150,
  noAutoFire        = false,
  objectName        = [[pylon.s3o]],
  seismicSignature  = 4,
  selfDestructAs    = [[ESTOR_BUILDINGEX]],
  side              = [[ARM]],
  sightDistance     = 273,
  smoothAnim        = true,
  TEDClass          = [[ENERGY]],
  turnRate          = 0,
  workerTime        = 0,
  yardMap           = [[ooooooooo]],

  featureDefs       = {

    DEAD  = {
      description      = [[Wreckage - Pylon]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 2000,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      height           = [[35]],
      hitdensity       = [[100]],
      metal            = 50,
      object           = [[ARMESTOR_DEAD]],
      reclaimable      = true,
      reclaimTime      = 50,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - Pylon]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 2000,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 50,
      object           = [[debris4x4b.s3o]],
      reclaimable      = true,
      reclaimTime      = 50,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - Pylon]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 2000,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 4,
      footprintZ       = 4,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 25,
      object           = [[debris4x4b.s3o]],
      reclaimable      = true,
      reclaimTime      = 25,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ pylon = unitDef })
