unitDef = {
  unitname           = [[timesline]],
  name               = [[New Year's Ball Detonator]],
  description        = [[Use with the cor New Year's Ball...]],
  acceleration       = 0,
  activateWhenBuilt  = true,
  antiweapons        = [[1]],
  bmcode             = [[0]],
  brakeRate          = 0,
  buildAngle         = 32700,
  buildCostEnergy    = 10,
  buildCostMetal     = 10,
  builder            = false,
  buildPic           = [[mahlazer.png]],
  buildTime          = 10,
  canAttack          = true,
  canstop            = [[1]],
  category           = [[SINK]],
  corpse             = [[DEAD]],
  defaultmissiontype = [[GUARD_NOMOVE]],
  energyUse          = 0,
  explodeAs          = [[SMALL_BUILDING]],
  footprintX         = 4,
  footprintZ         = 4,
  iconType           = [[mahlazer]],
  idleAutoHeal       = 5,
  idleTime           = 1800,
  mass               = 5,
  maxDamage          = 10,
  maxSlope           = 18,
  maxVelocity        = 0,
  maxWaterDepth      = 0,
  minCloakDistance   = 150,
  noChaseCategory    = [[FIXEDWING LAND SHIP SATELLITE SWIM GUNSHIP SUB HOVER]],
  objectName         = [[lazer.3do]],
  onoffable          = true,
  seismicSignature   = 4,
  selfDestructAs     = [[SMALL_BUILDING]],

  sfxtypes           = {

    explosiongenerators = {
      [[custom:IMMA_LAUNCHIN_MAH_LAZER]],
    },

  },

  side               = [[ARM]],
  sightDistance      = 660,
  smoothAnim         = true,
  TEDClass           = [[FORT]],
  turnRate           = 0,
  workerTime         = 0,
  yardMap            = [[oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo]],

  weapons            = {

    {
      def                = [[LAZER]],
      onlyTargetCategory = [[SATELLITE]],
    },


    {
      def                = [[TARGETER]],
      onlyTargetCategory = [[SATELLITE]],
    },

  },


  weaponDefs         = {

    LAZER    = {
      name                    = [[MAH LAZER]],
      accuracy                = 0,
      alwaysVisible           = 0,
      areaOfEffect            = 140,
      avoidFeature            = false,
      avoidNeutral            = false,
      beamlaser               = 1,
      beamTime                = 1,
      coreThickness           = 0.5,
      craterBoost             = 1,
      craterMult              = 2,
      cylinderTargetting      = 8192,

      damage                  = {
        default = 21,
        planes  = 21,
        subs    = 1.05,
      },

      energypershot           = 10,
      explosionGenerator      = [[custom:megapartgun]],
      impulseBoost            = 0,
      impulseFactor           = 0.4,
      interceptedByShieldType = 1,
      largeBeamLaser          = true,
      laserFlareSize          = 1.65,
      lineOfSight             = true,
      minIntensity            = 1,
      noSelfDamage            = true,
      range                   = 900,
      reloadtime              = 20,
      renderType              = 0,
      rgbColor                = [[1 1 0]],
      soundHit                = [[OTAunit/XPLOLRG1]],
      soundStart              = [[OTAunit/LASRMAS1]],
      texture1                = [[largelaser]],
      texture2                = [[flare]],
      texture3                = [[flare]],
      texture4                = [[smallflare]],
      thickness               = 1.64829457318769,
      tolerance               = 1000,
      turret                  = true,
      weaponType              = [[BeamLaser]],
      weaponVelocity          = 1400,
    },


    TARGETER = {
      name                    = [[MAH TARGETIN LAZER]],
      alwaysVisible           = 18,
      areaOfEffect            = 8,
      avoidFeature            = false,
      avoidNeutral            = false,
      beamDecay               = 0.736,
      beamlaser               = 1,
      beamTime                = 0.001,
      beamttl                 = 15,
      coreThickness           = 0.5,
      craterBoost             = 1,
      craterMult              = 2,
      cylinderTargetting      = 8192,

      damage                  = {
        default = 1,
        planes  = 1,
        subs    = 0.05,
      },

      energypershot           = 0,
      explosionGenerator      = [[custom:FLASH1blue]],
      impactOnly              = true,
      impulseBoost            = 0,
      impulseFactor           = 0,
      interceptedByShieldType = 1,
      largeBeamLaser          = true,
      laserFlareSize          = 9.78,
      lineOfSight             = true,
      minIntensity            = 1,
      noSelfDamage            = true,
      range                   = 9000,
      reloadtime              = 7,
      renderType              = 0,
      rgbColor                = [[0.25 0 1]],
      soundHit                = [[OTAunit/BURN02]],
      soundStart              = [[OTAunit/build2]],
      soundTrigger            = true,
      texture1                = [[largelaser]],
      texture2                = [[flare]],
      texture3                = [[flare]],
      texture4                = [[smallflare]],
      thickness               = 6.51920240520265,
      tolerance               = 10000,
      turret                  = true,
      weaponType              = [[BeamLaser]],
      weaponVelocity          = 1400,
    },

  },


  featureDefs        = {

    DEAD  = {
      description      = [[Wreckage - New Year's Ball Detonator]],
      blocking         = true,
      category         = [[corpses]],
      damage           = 20,
      energy           = 0,
      featureDead      = [[DEAD2]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[40]],
      hitdensity       = [[100]],
      metal            = 5,
      object           = [[ARMBRTHA_DEAD]],
      reclaimable      = true,
      reclaimTime      = 5,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    DEAD2 = {
      description      = [[Debris - New Year's Ball Detonator]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 20,
      energy           = 0,
      featureDead      = [[HEAP]],
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 5,
      object           = [[debris3x3c.s3o]],
      reclaimable      = true,
      reclaimTime      = 5,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },


    HEAP  = {
      description      = [[Debris - New Year's Ball Detonator]],
      blocking         = false,
      category         = [[heaps]],
      damage           = 20,
      energy           = 0,
      featurereclamate = [[SMUDGE01]],
      footprintX       = 3,
      footprintZ       = 3,
      height           = [[4]],
      hitdensity       = [[100]],
      metal            = 2.5,
      object           = [[debris3x3c.s3o]],
      reclaimable      = true,
      reclaimTime      = 2.5,
      seqnamereclamate = [[TREE1RECLAMATE]],
      world            = [[All Worlds]],
    },

  },

}

return lowerkeys({ timesline = unitDef })
