unitDef = {
  unitname            = [[timesball]],
  name                = [[New Year's Ball]],
  description         = [[Dropped from Logolas Square!]],
  acceleration        = 0.1,
  activateWhenBuilt   = true,
  amphibious          = true,
  bankscale           = [[0.5]],
  bmcode              = [[1]],
  brakeRate           = 3.75,
  buildCostEnergy     = 10,
  buildCostMetal      = 10,
  builder             = false,
  buildPic            = [[times.png]],
  buildTime           = 10,
  canAttack           = true,
  CanDropFlare        = 1,
  canFly              = true,
  canGuard            = true,
  canMove             = true,
  canPatrol           = true,
  canstop             = [[1]],
  canSubmerge         = false,
  category            = [[UNARMED SATELLITE]],
  collide             = false,
  cruiseAlt           = 600,

  customParams        = {
    helptext = [[YAY.]],
  },

  defaultmissiontype  = [[VTOL_standby]],
  explodeAs           = [[COMMANDER_BLAST_NEW_YEAR]],
  FlareDelay          = 0.3,
  FlareDropVector     = [[0 0 -1]],
  FlareEfficiency     = 0.3,
  FlareReload         = 5,
  floater             = true,
  footprintX          = 4,
  footprintZ          = 4,
  hoverAttack         = true,
  iconType            = [[scoutplane]],
  idleAutoHeal        = 5,
  idleTime            = 1800,
  maneuverleashlength = [[500]],
  mass                = 5,
  maxDamage           = 20,
  maxVelocity         = 5,
  minCloakDistance    = 75,
  noAutoFire          = true,
  noChaseCategory     = [[TERRAFORM SATELLITE FIXEDWING GUNSHIP HOVER SHIP SWIM SUB LAND FLOAT SINK]],
  objectName          = [[owl.s3o]],
  scale               = [[1]],
  seismicSignature    = 0,
  selfDestructAs      = [[SMALL_BUILDING]],
  side                = [[CORE]],
  sightDistance       = 50,
  smoothAnim          = true,
  stealth             = false,
  steeringmode        = [[1]],
  TEDClass            = [[VTOL]],
  turnRate            = 297,
  upright             = true,
  workerTime          = 0,

  weapons             = {
  },


  weaponDefs          = {
  },

}

return lowerkeys({ timesball = unitDef })
