-- IMPORTANT NOTES
--   Only works in Windows for now
--   Only attempt to run while in the same directory as the script
--   Run it ie. <path_to_lua>/lua.exe generatecards.lua
--   Overwrites all the files in the generatedtowers directory

-- where all generated towers are put into
local outputDirectory = "..\\units\\"

-- set to true to enable more debug output
local verbose = false

-- HACK: Lua does not support reading directory content directly
function ListFiles(query)
	dir = io.popen("dir /b "..query)
	files = {}
	for l in dir:lines() do
		if verbose then
			print("Found file: "..l)
		end
		table.insert(files,l)
	end
	return files
end

function VerifyVarType(fromTable,variableName,variableType)
	if (type(fromTable[variableName]) ~= variableType) then
		print("Fatal error: Variable '"..variableName.."' should be "..variableType)
		os.exit()
	end
end

function LoadCardsFromDirectory(dir)
	mainDirectory = "lua\\"
	path = mainDirectory .. dir .. "\\"
	if verbose then
		print("Loading directory: "..dir)
	end
	query = path .. "*.lua"
	cards = {}
	for _,scriptFile in pairs(ListFiles(query)) do
		card = dofile(path .. scriptFile)
		if (type(card) ~= "table") then
			print("Fatal error: Did not get table from "..scriptFile)
			os.exit()
		end
		VerifyVarType(card,"name","string")
		table.insert(cards,card)
	end
	return cards
end

function SimplifyString(str)
	-- Anything that is not alphanumeric is removed and string is turned to lowercase
	return string.lower(string.gsub(str,"[^%w]",""))
end

function CopyFile(source,destination)
	local file = io.open(source,"r")
	if not file then
		print("Copy failed!! Missing "..source)
		return
	else
		file:close()
	end
	if verbose then
		print(source.." to "..destination)
	end
	io.popen("copy /y "..source.." "..destination)
	local file = io.open(source,"r")
	if not file then
		print("Copy failed for "..source)
		return
	else
		file:close()
	end
end

materialCards = LoadCardsFromDirectory("material")
weaponCards = LoadCardsFromDirectory("weapon")
print("Loaded "..#materialCards.." material cards, "..#weaponCards.." weapon cards")

local towers = {}
for _,material in pairs(materialCards) do
	for _,weapon in pairs(weaponCards) do
	
		-- Variables present in both cards will be combined, numbers added together and strings concatenated
		local combined = {}
		for key,_ in pairs(weapon) do
			-- Template in weapon card tells us the weapon template to use for the unit definition
			if key == "template" then
				combined["weaponTemplate"] = weapon[key]			
			elseif material[key] then
				-- The variable is present in both cards, now need to combine the values
				if type(material[key]) == "number" and type(weapon[key]) == "number" then
					combined[key] = material[key]+weapon[key]
				elseif type(material[key]) == "string" and type(weapon[key]) == "string" then
					combined[key] = material[key]..weapon[key]
				else
					print("WARNING: Ignoring "..key.." variable!!")
				end
			else
				-- The variable is present in only in the weapon card
				combined[key] = weapon[key]
			end
		end
		for key,_ in pairs(material) do
			-- Template in material card tells us the base template to use for the unit definition
			if key == "template" then
				combined["materialTemplate"] = material[key]
				
			-- HACK: The actual 3d filename is not named after the original unit name in these cases
			elseif key == "model" then
				if material[key] == "armllt" then
					combined[key] = "novallt"
				elseif material[key] == "armhlt" then
					combined[key] = "novahlt"
				else
					combined[key] = material[key]
				end
				
			elseif not weapon[key] then
				-- The variable is present in only in the material card
				combined[key] = material[key]
			end
		end
		-- This name will be used for the filename, unit name etc
		combined["shortname"] = SimplifyString(combined["name"])
		table.insert(towers,combined)
	end
end

local count = 0
for _,tower in pairs(towers) do
	local materialTemplate = "towertemplates\\materials\\"..tower["materialTemplate"]..".lua"
	local weaponTemplate = "towertemplates\\weapons\\"..tower["weaponTemplate"]..".lua"
	file = io.open(outputDirectory..tower["shortname"]..".lua","w")
	if not file then
		print("Fatal error: Unable to open file for writing: "..tower[name])
		os.exit()
	end
	if not tower["materialTemplate"] then
		print("Fatal error: Material template missing for "..tower["name"])
		os.exit()
	end
	file:write("--WARNING\n--This file is automatically generated and all manual changes will be lost!!\n\n")
	-- TODO: Check and do something if template file is missing
	for line in io.lines(materialTemplate) do
		if string.match(line,"%%WEAPONS%%") then
			if tower["weaponTemplate"] then
				-- TODO: Check and do something if template file is missing
				for weaponLine in io.lines(weaponTemplate) do
					if string.match(weaponLine,"%%%%") then
						for key,value in pairs(tower) do
							pattern = "%%%%"..string.upper(key).."%%%%"
							weaponLine = string.gsub(weaponLine,pattern,value)
						end
					end
					file:write(weaponLine.."\n")
				end
				line = ""
			else
				print("Fatal error: Weapon template missing for "..tower["name"])
				os.exit()
			end
		elseif string.match(line,"%%%%") then
			for key,value in pairs(tower) do
				pattern = "%%%%"..string.upper(key).."%%%%"
				line = string.gsub(line,pattern,value)
			end
		end
		file:write(line.."\n")
	end
	file:close()
	CopyFile("..\\scripts\\"..tower["model"]..".cob", "..\\scripts\\"..tower["shortname"]..".cob")
	CopyFile("..\\scripts\\"..tower["model"]..".bos", "..\\scripts\\"..tower["shortname"]..".bos")
	count = count + 1
end
print("All done! Generated "..count.." towers.")